### ISSUE TITLE
Update the Readme.md

### ISSUE THREAD

**Issue by Laurentjg** [alliander-opensource/der-scheduling#2]
Hi, 
It's unclear how anybody can contribute code, comments, bugreporting, etc to this project. Normally this is written in the README.MD file. Can you give more clarity about this? An introduction with the context and aimed goals would also be nice ;-)

**Comment by Sander3003** [comment]
@Laurentjg it his fixed now?

**Comment by Laurentjg** [comment]
Yes, it is!
